CREATE TABLE STUDENTS
(
    ID                 BIGSERIAL      NOT NULL PRIMARY KEY,
    NAME              VARCHAR(255)   NOT NULL,
    AGE               INT NOT NULL);


INSERT INTO STUDENTS (NAME, AGE) VALUES('Viktor Ivanov', '36');
INSERT INTO STUDENTS (NAME, AGE) VALUES('Maria Petrova', '21');
INSERT INTO STUDENTS (NAME, AGE) VALUES('Alexandr Sidorov', '19');
INSERT INTO STUDENTS (NAME, AGE) VALUES('Anna Popova', '20');
INSERT INTO STUDENTS (NAME, AGE) VALUES('Dmitriy Frolov', '22');